name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greetings_job:
    runs-on: ubuntu-latest
    env:
      Greetings: Hello
    steps:
      - name: "Say Hello David it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: David
