name: CI - Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  # asegúrate que tu proyecto use esta versión

      - name: Restore dependencies
        run: dotnet restore ./ExploringActions2/netcore/ExploringActions2/ExploringActions2.sln

      - name: Build
        run: dotnet build ./ExploringActions2/netcore/ExploringActions2/ExploringActions2.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./ExploringActions2/netcore/ExploringActions2/ExploringActions2.csproj --no-build --configuration Release --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./ExploringActions2/netcore/ExploringActions2/TestResults/TestResults.trx
