name: .NET Core Unit Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x' # o la versión que estés usando

      - name: Restore dependencies
        run: dotnet restore ./ExploringActions2/netcore/ExploringActions2/ExploringActions2.sln

      - name: Build
        run: dotnet build ./ExploringActions2/netcore/ExploringActions2/ExploringActions2.sln

      - name: Run tests
        run: dotnet test ./ExploringActions2/netcore/ExploringActions2/ExploringActions2.sln

